### ISSUE TITLE
【不具合？】「動画」→「公開順」で表示される動画を前の仕様に戻してほしい

### ISSUE THREAD

**Issue by tasogale** [garplab/typingtube#103]
前まではYoutube上で公開された順に、公式PV or カバーPV のタグが付けられたかどうかに関わらず表示されていたが、今は 公式 or カバーPV のタグが付けられた順に表示されている。(多分)
トップページの新着順の「もっと見る」で表示されるものと同じになっているので、前の仕様に戻してほしい。

**Comment by garplab** [comment]
こちら、対応しない予定です
