### ISSUE TITLE
やり直し時の記録送信について

### ISSUE THREAD

**Issue by Toshi7878** [garplab/typingtube#111]
TypingTubeのsubmit_score関数をやり直し時(10打鍵以上していた場合)に呼び出していることで、
現在やり直し分の記録もランキングに登録されるようになっているのですが、
プレイ終了時の記録のみをランキング登録 ＆ タイムラインに表示されるようにすることは可能でしょうか？

やり直し分の記録は総合打鍵回数のカウントのみされる仕様にして欲しいです。

プレイ終了しているかの判定で使われている変数 finished を送信することで判別できそうです。
可能であれば、検討おねがいします。

**Comment by garplab** [comment]
対応済み
