### ISSUE TITLE
【不具合】タイピングデータのスコアランキングで下位のスコアが表示されなくなっている

### ISSUE THREAD

**Issue by Toshi7878** [garplab/typingtube#113]
いままでの登録されていた一部のスコア(下位のみ？)が表示されなくなっています。

上記の現象が発生している譜面と発生していない譜面が存在します。

下記URLの譜面が顕著に下位のランキング登録者が非表示になっています。

https://typing-tube.net/movie/show/23640

**Comment by Toshi7878** [comment]
https://twitter.com/NarotsuNurobusi/status/1550121940895305728

**Comment by garplab** [comment]
表示数を増やしました、数が多いと負荷がかかるので工夫しないといけないですが、下位のランキングもできるだけ表示できるように今後調整していきます
