### ISSUE TITLE
データ制作のダッシュボードにアクセスできない

### ISSUE THREAD

**Issue by tasogale** [garplab/typingtube#117]
もともとダッシュボードのページは表示されるのが遅い気がしていましたが、半年ほど前から特に遅くなったように感じます。
また、そのころからたまに「504 Gateway Time-out」が発生するようになった気がします。
それがだんだん悪化してきて、1ヵ月前は20回ほど更新することでやっとアクセスできるぐらいになり、今日は50回以上更新してもアクセスできません。ずっと「504 Gateway Time-out」が表示され続けます。
データ制作数が多すぎるのが問題なのか？と思い、試しに何の実績もないアカウント(データ制作もプレイもなし)でアクセスしてみたところ、すぐに表示されました。

タイムアウトの理由がデータ制作数の多さによるものなのかはわかりませんが、ダッシュボードが表示されるよう、改善できないでしょうか。

**Comment by garplab** [comment]
負荷の大きいグラフを削除して復旧しました
