### ISSUE TITLE
プロフィール画面の「データ制作数」更新されていない

### ISSUE THREAD

**Issue by tasogale** [garplab/typingtube#124]
プロフィール画面の「データ制作数」の数字が一か月程前から更新されなくなっています。
「満点獲得数」、「100%クリア数」、「80%クリア数」、「1位チャンネル数」はちゃんと確認していないのでわからないです。
おそらく、2/17か2/18ごろからです。

データ制作のダッシュボードに表示される「制作数」は、正しい数字のようです。

**Comment by garplab** [comment]
@tasogale 
ありがとうございます。更新されなくなっていた不具合を修正しました。
他の数字も更新されていると思います。
