### ISSUE TITLE
データ制作のダッシュボードが繋がりにくい

### ISSUE THREAD

**Issue by tasogale** [garplab/typingtube#125]
以前にも同じようなことを報告したことがあります(#117)が、最近またデータ制作のダッシュボードに繋がりにくくなっています。
以前と同様に、"504 Gateway Time-out"が表示されます。
表示項目を減らした後、「総いいね数」を追加されたと思うのですが、その時期から少しずつ繋がりにくくなりました。

また、アクセスできたときに「制作数推移」と「Ranking登録数推移」のグラフが表示されない場合もあります。

繋がりにくくなったのは私だけかもしれませんし、困ってるわけではないので、すぐに対応して欲しいとかではないです。

**Comment by garplab** [comment]
@tasogale 
計算できなくなっているグラフを削除して復旧しました
今後、別途事前集計する仕組みを作った上で表示の再開を検討したいと思います。
