### ISSUE TITLE
打/秒の計算式

### ISSUE THREAD

**Issue by Toshi7878** [garplab/typingtube#15]
タイピングガチな人は大体、打鍵の速さを重要視するので
実際の速度がわかると人口増える。絶対。

**Comment by garplab** [comment]
計算が合ってないプレイ履歴やどんな風に計算が異なっているのかなどをおしえてください。

調査や動作確認が難しいので、なかなかこの手の修正が進まないので、具体的に教えてもらえると助かります。

**Comment by Toshi7878** [comment]
現時点で分かっているのは
・タイピングデータの入力文字数が多いほど打/秒の数値が大きくなる
・数値が蓄積されている？
(タイピング速度検定の打鍵/秒では経過時間1秒毎に計算している)
sl.infovision.co.jp/t.php
ぐらいです；

タイピング速度検定と違って入力受付時間が曲によって変わるので
打鍵速度周りの修正難しそうですね(ﾟｰﾟ;

まだテストしてないので何か分かったら、また報告します

**Comment by fire1192** [comment]
Google Devloper Toolsでちょっとした実験を行ってみました。
type_per_min = (typing_count / (playing_sec * 60));
ここに問題がありそうです。
playing_secはfunction playheadUpdate()のたびにほぼ毎回更新されて、
playing_sec = headtime - timebuf;
という計算式です。このfunctionが59~60fpsの間隔で呼ばれていました。なので実質的に
type_per_min≒typing_count;
のような感じになっていてこれが蓄積の原因だと考えました。
別の変数playing_time, playing_time_current（名前は適当）を用意して、これらをタイピングを行っている時間として
lyrics_array[now][2 ( or 1) ]が空でないときに
playing_time_current = time_buf - lyrics_array[now - 1][0];
で現在のタイピングフレーズの経過時間を取得して、フレーズ終了時（タイピング完遂時含む）に
playing_time += playing_time_current;
playing_time_current = 0;
を行い、type_per_minの計算を
type_per_min = typing_count / ((playing_time + playing_time_current) * 60);
とすることで解決できないでしょうか？
ざっとコードを確認しただけかつデバッグなどはやっていないので間違っていたら申し訳ないです。ご参考いただければ幸いです。

**Comment by Toshi7878** [comment]
fire1192さんの改善案を参考にさせて頂き、User Scriptから打/秒の表示に成功したので報告します
以下のスクリプトはplayheadUpdate()関数内でtyping_speedの計算をしていますが
User Scriptでの検証時は[変数を監視する関数](https://risaki-masa.com/function-for-observing-variable-with-js/)を使用しました

var line_sec = 0; //現在のライン経過時間
var playing_time = 0; //過去の合計ライン経過時間
var playing_time_current = 0; //現在のライン経過時間+過去の合計ライン時間
var typing_speed = 0; //打/秒

var line_clear = false;
var count_save = false;


      function playheadUpdate() {
if(line_input.length != 0){//入力する文字が存在する
line_sec = time_buf - lyrics_array[count - 1][0] //現在のライン経過時間算出(ラインが切り替わる度、0になる)
playing_time_current = line_sec + playing_time　//累計経過時間
typing_speed = ((typing_count/playing_time_current)).toFixed(2) //打/秒
}

if(completed && !line_clear){//ラインクリアした時
            playing_time += line_typetime//ラインクリアした時の経過時間を加算
playing_time_current= playing_time //累計経過時間を固定
        line_clear = true; //flag
}
if (isNaN(typing_speed)) {
          typing_speed = 0;
}

if(count != count_save && already_input.length == 0 && count >= 2){//次のラインに移動した
count_save = count
    if(lyrics_array[count - 2][2].length != 0 && !line_clear){//一つ前が間奏ラインではない時 && ラインクリアしていない時
playing_time += lyrics_array[count - 1][0]-lyrics_array[count - 2][0] //ラインクリアしていないので、直前のライン時間を全て累計時間に加算
    }else if(line_clear){//ラインクリアしていたらフラグのみ初期化
        line_clear = false
}
}
}
      function update_status() {
          let correct = typing_count / (typing_miss_count + typing_count) * 100.0;
          if (isNaN(correct)) {
            correct = 0;
          }
          $("#status").html( Math.floor(parseInt(score)/20)/100 + "点<br>" + typing_miss_count + "回miss<br>" + max_combo + "コンボ" + "<br>correct: " + correct.toFixed(2) + "%<br>" + complete_count + " clear / " + (complete_count + failer_count) + " line<br> " + typing_speed + " 打/秒");
          update_skip();
      }

**Comment by fire1192** [comment]
予想はしていましたが動画の再生速度に倍率をかけている場合は正しく計算されませんね…
手軽に解決しようとするならラインごとの打鍵速度計算にplay_speed値を組み込むことでしょうか。
~~うまく再生速度をいじることで打鍵速度だけ早く見せかけることができそう…~~

**Comment by Toshi7878** [comment]
fireさん参考になります！(typing_count/(経過時間/player.getPlaybackRate())で倍率を変化させた時、一緒に打鍵速度も対応した数値にすることができました！

あと、time_buf変数でちょっとした発見があったので報告します

time_buf変数はHTML2595行目のif文で、ラインクリアしていない時に
変数headtime = player.getCurrentTime() + player.difftime;経由での数値を取得していますが、
タイピングデータは必ずしもlyrics_array[count].length == 3ではないみたいです

対策方法は、ライン切替時に→ if(lyrics_array[count].length == 2){ lyrics_array[count].push('') }
をすることで解消できました

**Comment by fire1192** [comment]
lyrics_array[count].length==2となるのはTyping-tubeの歴史に関係がありそうです（新参者なのでわかりませんが古い動画の空白ラインによく見られました）。show/22143 以降修正？
/*
話の本筋からそれ、かつMODの話になってしまい本当に申し訳ないのですが、show/10002 の動画でlyrics_arrayの確認をしたのですが、lyrics_array[13]の「wow wow yeah yeah」の歌詞の場面でtyping-tube mod v5.50を使用していると画面端のアイコンが８割□になる不具合が存在している可能性があります。原因は分かりませんでしたが報告しておきます。
*/

**Comment by Toshi7878** [comment]
報告ありがとうございます！
不具合の原因ですが、ミスマーク表示の処理で「ミスした時stylesheet.insertRule(0)で赤文字の上に「・」マーク追加 ⇒ combo == 1又はcountが更新されたらstylesheet.deleteRule(0);で「・」マーク削除」という処理をしていたのが原因でした。

文字のセンターに「・」マークを表示させたいのでnext_charの１文字目を見て、その文字に該当するCSSをstylesheet.insertRule()で追加していたのですが、全角英字だった時にCSSを追加する処理処理を記述していなかった為...
全角英字をミス → stylesheet.insertRule(0)が発動しない → ミス復帰するとcombo == 1になる又はcountの数値が増える → stylesheet.deleteRule(0);が発動してサイトに元々あったCSSが削除される

という流れでアイコンが８割□になる不具合が起きていました
