### ISSUE TITLE
青色ラインが右端に到達する前に切り替わる

### ISSUE THREAD

**Issue by Toshi7878** [garplab/typingtube#16]
青色ラインが常に右端に行く前に切り替わってしまう。TypingTubeのタイピング環境に慣れが必要になってくる
Twitterで何度かこの問題を呟いている人を見かけた

**Comment by garplab** [comment]
これはちょっと難しいかもです。
右端まで青くする描画処理の前に次のラインの表示が始まってしまっているので、
内部の処理を整理して高速化したり、仕組みを変更する必要がありそうです。

とりあえず、対応保留します。

**Comment by Toshi7878** [comment]
修正しました
progressタグに変更し進捗バーをvalueに設定することで、右端に到達するまで描写できるようになりました

以下のuser scriptでHTML読み込み時にprogressタグのバーに差し替える処理をしているので、
ロード時はバーが2つ表示されます

https://greasyfork.org/ja/scripts/404258-typing-tube-%E3%83%87%E3%83%90%E3%83%83%E3%82%B0-%E3%83%A9%E3%82%A4%E3%83%B3%E3%83%90%E3%83%BC-%E5%8B%95%E7%94%BB%E6%99%82%E9%96%93%E3%83%90%E3%83%BC%E4%BF%AE%E6%AD%A3

**Comment by Toshi7878** [comment]
スクリプトを更新しました
end処理の後にmax_value値を決めるように変更しました

**Comment by Toshi7878** [comment]
スクリプトを更新しました
getScorePerChar()関数でendのライン番号を取得し、「#bar_baseのmax値=end行の時間」とするように変更

**Comment by Toshi7878** [comment]
すみません
動画時間のバーがうまく動作していなかったので修正しました

**Comment by Toshi7878** [comment]
Typing Tube MOD official
で修正されています
