### ISSUE TITLE
ランダム選曲(要望)

### ISSUE THREAD

**Issue by StE-Sakurama** [garplab/typingtube#22]
ランダムでレベルごとの曲をプレイする機能が欲しいです。

**Comment by garplab** [comment]
同じレベルの曲のオススメが２曲追加で出るようにしてみました。
現在、以下の８曲がページ下部におすすめとして表示される仕様です。
- 必ず同じレベルの曲２曲表示
- レベル関係なく同じチャンネルの曲がランダムで４曲表示＋レベル関係なく全ての曲からランダムで２曲表示
