### ISSUE TITLE
タイピングデータ作成時の"結合"時の改善要望

### ISSUE THREAD

**Issue by fire1192** [garplab/typingtube#23]
タイピングデータ作成で「↑結合↑」ボタンで結合を行う際に読み仮名の方に半角空白が入ってしまうのを入らない仕様に変更してもらいたいです。理由としては、そのまま保存するとプレイ時にその場所で半角スペース待機が発生しタイピングの妨げとなることがあるからです。検討をお願いします。

**Comment by garplab** [comment]
ありがとうございます。対応しました
