### ISSUE TITLE
タイピング時のラインカウントの不具合

### ISSUE THREAD

**Issue by fire1192** [garplab/typingtube#24]
タイピングフレーズの一番最後の文字だけ残した状態でフレーズを終了するとラインカウント（clear , line両方とも）がカウントされないようです。
ex )
 **パプリカ花が咲いたら晴れた空に種をまこ**　う
太字の文字が入力済状態です。また、
**ハレルヤ　夢を描いたなら　心遊ばせあなたにとど**　_け_
の最後の文字"け"の k だけ打ち込んだ状態でも同様の現象が発生しました。

**Comment by Toshi7878** [comment]
修正できているのでcloseしても大丈夫そうです

**Comment by fire1192** [comment]
了解しました。
