### ISSUE TITLE
新規作成でタイピングデータを作成時、We're sorry, but something went wrong.が出てしまう

### ISSUE THREAD

**Issue by Toshi7878** [garplab/typingtube#27]
新規作成でタイピングデータを保存したあと後、[早速プレイして確認したり、タグを設定する]を押すとWe're sorry, but something went wrong.と書かれたページに飛ばされてしまいます
難易度が決定されるまでの間はこのエラーが出てしまうみたいです

**Comment by garplab** [comment]
こちら対応完了しました
