### ISSUE TITLE
「ん」のタイピングについて

### ISSUE THREAD

**Issue by ghost** [garplab/typingtube#29]
例えば，「こんな」を打つときに，`KONNA`と打ってもOKになってしまいます．
(本来なら，`KONNNA`や`KOXNNA`と打たなくてはいけない，`KONNA`だと「こんあ」になってしまう)
また，各行の最後に「ん」が来るときにも，N 1個でラインクリアに鳴っているような気がします．
普通に打っていれば何も問題はないのですが，気になるので修正をお願いしたいです．

**Comment by ghost** [comment]
追記
「なんおく」も`NANOKU`でOKになってしまいます．

**Comment by garplab** [comment]
こちら対応しました

**Comment by Toshi7878** [comment]
https://typing-tube.net/movie/show/3721 (自分が使用しているテスト用データ)
に「ん」の入力パターンが変化する組み合わせの入力文を作成して検証しました
~~「んな」~「んの」は対応できていましたが、他のパターン~~

「んあ」\~「んお」
「んや」\~「んよ」
「んん」
「ん+アルファベット」
文末の「ん」

以上のパターンのときはまだ[n]単体でも通ってしまいます}

追記 2020/3/23
こちらの確認ミスでした
「んな」\~「んの」もn単体で通ってしまうのを確認しました

**Comment by ghost** [comment]
自分より を `JIBUNNYORI` と打つと2回目のNがミス判定になってしまいます。
また、ん とは関係ないのですが、例えば「たこ」を打つときに、こ を`CO`で打とうと思ってから`KO`にしようとして、`TACKO`と打ってもミス判定にはならないようです。(#21に細かく書いてあります)
せっかくなので、これらも修正をお願いしたいです。

**Comment by ghost** [comment]
Toshi1999 さんのデータを使わせていただきました。
どうも、んを`NN`で打つとミス判定になってしまうようですね…
また、現在(2020/03/23 21:18)時点では「ん」＋な行も対応されていないようですが…

**Comment by ghost** [comment]
現在(2020/04/05 11:23)時点で、文末を除く全ての「ん」について、`NN` で打つとミス判定になってしまっています。(`XN`は大丈夫な模様) 正直、これはタイピング練習サイトとしてはかなり致命的なバグかと思います。
「ん」＋か行など、`N` 単独でもタイプ可能なところはまだいいのですが(cf. ベネッセタイピング)、最低限Toshi1999さんの挙げられている、「ん」＋あ行などについては`NN` or `XN` に対応をお願いします。
いつもTyping Tubeを楽しませてもらっています。プレイ人口を増やすためにも、ぜひ早急な対応をお願いします。

**Comment by garplab** [comment]
ありがとうございます。対応しました。

**Comment by ghost** [comment]
現在(2020/04/05 13:57)時点で、例えば「参加」を`SANKA`と打つとNが2個必要な判定になってしまっています。「ん」の後が `A` `I` `U` `E` `O` `N` `Y`  のときは `NN` または `XN` 、それ以外のときは `N`、`NN`、`XN` のいずれでも対応をお願いします。

**Comment by Toshi7878** [comment]
アルファベット[A I U E O N Y]だけでなく「ん」の後が「半角文字」のときはNN, XNの判定にしたほうが良いと思います(数多くのタイピングサイトはその仕様)

参考程度にJavascriptのreplaceを作成すると「ん」の入力パターンの正規表現はこんな感じになります
　```
.replace(/んあ/g,'nna')
    .replace(/んい/g,'nni')
    .replace(/んう/g,'nnu')
    .replace(/んえ/g,'nne')
    .replace(/んお/g,'nno')
    .replace(/んや/g,'nnya')
    .replace(/んゆ/g,'nnyu')
    .replace(/んよ/g,'nnyo')
    .replace(/んな/g,'nnna')
    .replace(/んに/g,'nnni')
    .replace(/んぬ/g,'nnnu')
    .replace(/んね/g,'nnne')
    .replace(/んの/g,'nnno')
    .replace(/(ん)([!-~])/g,'nn$2')
    .replace(/[ん]$/,'nn')
    .replace(/んん/g,'nnn')
    .replace(/ん/g,'n')

```

**Comment by ghost** [comment]
今(2020/04/05 20:57)現在確認したら直っていました！
日本語タイピングとしては満足です。
Toshi1999さんの仰る「ん」＋半角英数字について、もちろんそこも直してくれればより良いのかもしれませんが私としてはこれで満足です(*^^*)
これから3日間ほど使ってみて、問題ないようならCloseします。
修正ありがとうございました。
