### ISSUE TITLE
settingページから動画の画質を変更しても画質が変更されない

### ISSUE THREAD

**Issue by Toshi7878** [garplab/typingtube#31]
https://typing-tube.net/my/edit
settingページにて、動画の画質を変更しても、HTML上に表示される動画サイズは適応されますが、iframe内の動画の画質はlarge設定になっています。

consoleからplayer.getPlaybackQuality()関数を使用して確認できました

**Comment by Toshi7878** [comment]
mediumも確認できたので、YouTubeの自動設定が効いているみたいです

**Comment by garplab** [comment]
こちら調整大変なので、一旦未対応とさせていただきます。
