### ISSUE TITLE
Firefoxでアポストロフィーを入力するとブラウザのクイック検索ウィンドウが出てしまう

### ISSUE THREAD

**Issue by Toshi7878** [garplab/typingtube#33]
Firefoxでタイピングプレイ中にアポストロフィー[']を入力するとブラウザのクイック検索機能のショートカットキーが発動してしまいます。以下の条件分岐でショートカットキーを無効化できます

if(event.shiftKey && event.keyCode ==55) {//Firefoxのクイック検索ショートカットキーを無効化
        event.preventDefault();
        }

**Comment by Toshi7878** [comment]
追記
/キーでもクイック検索機能が発動したので分岐条件は以下のほうがいいかもしれないです
if(event.shiftKey && event.keyCode ==55 || event.keyCode ==191) {//Firefoxのクイック検索ショートカットキーを無効化
event.preventDefault();
}

**Comment by garplab** [comment]
ありがとうございます。修正してみたけど、いかがでしょうか？

**Comment by Toshi7878** [comment]
検証しました！
まだFirefoxで[']と[/]をタイピングプレイ中に打ってしまうとクイック検索機能が発動してしまいます...
実際の挙動を画像に書いてみました

![2020-3-22_10-4-49_No-00_NoName](https://user-images.githubusercontent.com/38578537/77240130-bf761c80-6c25-11ea-9bad-c6e4f21b3ccb.jpg)

**Comment by Toshi7878** [comment]
Typing Tube MOD ver.26.0.6
修正しました
