### ISSUE TITLE
100点を取ってもタイムラインに反映されない

### ISSUE THREAD

**Issue by TakumiABM** [garplab/typingtube#34]
https://typing-tube.net/movie/show/30095
上のデータで100点を取りましたがタイムラインに反映されていません。
詳しく調べていないのでわかりませんが、80%クリア、100%クリアに関しても同じ状態のように感じます。

**Comment by garplab** [comment]
ありがとうございます！助かります。プレイ後サーバ側の処理に問題があったので、修正しました。
