### ISSUE TITLE
肩書き設定の選択項目でデイリーミッションが重複している

### ISSUE THREAD

**Issue by Toshi7878** [garplab/typingtube#36]
細かな不具合ですが報告します
デイリーミッションをクリアする度に追加されている？
![2020-3-24_1-24-13_No-00_NoName](https://user-images.githubusercontent.com/38578537/77338819-39b1b880-6d6e-11ea-8574-f9ac8eb4cba4.jpg)

**Comment by garplab** [comment]
ありがとうございます！こういうの助かります。
修正しました
