### ISSUE TITLE
全画面でないときにコミュニティとデイリーミッションのドロップダウンリストが追従しない

### ISSUE THREAD

**Issue by TakumiABM** [garplab/typingtube#44]
全画面のときは問題ありませんが、アドレスバーなどが表示されている状態だと正常に動きません。ChromeとFirefox(一応iPhoneのChromeでも)で確認しました。

![コメント 2020-04-16 161747](https://user-images.githubusercontent.com/48353713/79426796-a41ce800-7ffe-11ea-8fa5-11a932f9afd0.png)
![コメント 2020-04-16 161802](https://user-images.githubusercontent.com/48353713/79426853-be56c600-7ffe-11ea-9135-675dffc479dd.png)

**Comment by garplab** [comment]
いつの間にか治ってるかもしれないです。今は再現しなかったです

**Comment by TakumiABM** [comment]
デイリーミッションは直りましたがコミュニティがダメっぽいですー
報告してなかったんですが、コミュニティについてはChromeだと全画面じゃなくてもブックマークバー非表示でなぜか直るみたいです
![image](https://user-images.githubusercontent.com/48353713/80300189-67f33f80-87d5-11ea-93dc-a22fe75959da.png)
![image](https://user-images.githubusercontent.com/48353713/80300229-cc160380-87d5-11ea-96ae-a99d03763d3a.png)
