### ISSUE TITLE
Bad Apple Full Versionのバグ

### ISSUE THREAD

**Issue by ghost** [garplab/typingtube#45]
(Toshi(test))さんの作成したBad Apple Full Versionでいろんなものが消えます。
記号(例えば？など)を打つ際に打ち込んでる文字を表示している場所が消えます。
あと、今回のアップデートで追加されたフリガナ表記のほうは残るのですが、
ローマ字表記が最初から最後まで表示されません。
因みにローマ字表示でプレイしています。
また、打ち込み切ってないのに文字の表示が消えます

**Comment by Toshi7878** [comment]
修正します！

**Comment by ghost** [comment]
迅速な対応ありがとうございます！
