### ISSUE TITLE
【要望】編集画面で5秒程度のスキップ・巻き戻し機能がほしい

### ISSUE THREAD

**Issue by TakumiABM** [garplab/typingtube#47]
データを作っていると、長い歌詞や、最後の音を伸ばした歌い方をしている部分など、飛ばした方が時短になるなーと思うところがよくあるのですが、そのような時、左右矢印キーなどでシークバーより簡単にスキップ・巻き戻しができるショートカットがあると便利だと思います。
スキップ・巻き戻しの時間は自由に設定できたら嬉しいのですが、難しい場合はYouTubeと同じで両方とも5秒が良いと思います。

12日に動画を再生したままシークバーを操作できるようにしてほしいという要望を出しましたが、リクエストしておいてなのですが、個人的にこちらの機能があればシークバーは操作できなくても特に問題ないです。

**Comment by Toshi7878** [comment]
Tampermonkeyを使用して実装できそうだったので、エディタで←→キーを押すことで5秒スキップ・巻き戻しができる機能サンプルを作成してみました

https://greasyfork.org/ja/scripts/401306-typing-tube-エディタ-←→キーで5秒スキップ・巻き戻しサンプル

ブラウザに[Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=ja)アドオンを導入することでスクリプトをインストールすることができます

**Comment by TakumiABM** [comment]
ありがとうございます！
これでかなり作りやすくなりそうです！
