### ISSUE TITLE
譜面作成できない

### ISSUE THREAD

**Issue by jumpaction** [garplab/typingtube#48]
![image](https://user-images.githubusercontent.com/61897009/79679314-d8331b80-823f-11ea-84c8-886b1c20a60b.png)
作成開始を押すと、、
![image](https://user-images.githubusercontent.com/61897009/79679318-e8e39180-823f-11ea-9777-5195db995cf2.png)

**Comment by TakumiABM** [comment]
動画のURLは入力されているでしょうか？
現在のところURLを入力せずに作成開始を押すとエラーが出る仕様になっています。

**Comment by garplab** [comment]
こちら問題なさそうなのでcloseします。
