### ISSUE TITLE
外部サイトでの利用を許可されていない動画は、新規作成時のURLを送信した時点で教えてほしい

### ISSUE THREAD

**Issue by Toshi7878** [garplab/typingtube#50]
新規作成時に指定した動画に埋め込み制限がかかっているときは、保存ボタンを押したあとでしかチェックできないので
「データ作成後に保存ボタンを押す→外部サイトでの利用が許可されていない→せっかく作成したデータがアップロードできない」
という事故が起こり得ると思います

URLを送信した時点でチェックできると良いと思います
![2020-4-25_20-11-2_No-00_NoName](https://user-images.githubusercontent.com/38578537/80278486-aafbd700-8731-11ea-90dd-ac7ac86e320d.png)

**Comment by garplab** [comment]
埋め込み制限がかかっている場合、編集画面でも利用できないはずです。
発生したら、発生した動画を教えてください

**Comment by Toshi7878** [comment]
再生できないの確認できました！お騒がせしました
Closeします
