### ISSUE TITLE
制作者コメント付きのデータを強制編集できない

### ISSUE THREAD

**Issue by TakumiABM** [garplab/typingtube#51]
制作者コメントが付いているデータを強制編集しようとすると「コメントを強制編集することはできません」というメッセージが表示されて編集することができません。
ちゃんと確認していないのでもっと細かい条件があるかもですが、以下のデータで確認しました。
https://typing-tube.net/movie/show/16281

**Comment by garplab** [comment]
「コメントを強制編集することはできません」というメッセージを表示しないようにして対応しました
