### ISSUE TITLE
リクエスト曲を制作したのに、デイリーで反映されない。

### ISSUE THREAD

**Issue by yamaneko828** [garplab/typingtube#52]
同様に、制作した3本のリクエスト曲の内、制作後 2曲のポイント付与が行われませんでした。
リクエスト曲関連の不具合が多いので修正お願い致します。

**Comment by garplab** [comment]
ポイント付与は一部だけです。今後ポイントをリクエストした人が追加する機能など検討してます。
不具合見つけたら個別に再現方法等記載してissue作っていただけると助かります。

**Comment by Toshi7878** [comment]
直っているので、closeしても問題ないと思います
