### ISSUE TITLE
[要望]練習モードでも普通にPlayした時と同じようにリザルトを表示してほしい。

### ISSUE THREAD

**Issue by ghost** [garplab/typingtube#53]
練習モードでも普通にPlayした時と同じように制限時間以内にクリアできたラインには[clear],制限時間内にクリアできなかったラインには[failure]と表示して頂きたいです。自分がどれだけ出来たか,自分がどれだけどこが出来なかったかが分かるので...

**Comment by Toshi7878** [comment]
練習モードでも待ち合わなかったラインはfailureが表示されるようになりました

**Comment by ghost** [comment]
ありがとうございました！
