### ISSUE TITLE
【不具合】ログインしている状態での検索のオプションの機能

### ISSUE THREAD

**Issue by fire1192** [garplab/typingtube#55]
ログインしていないときと、ログインしている時で検索の挙動が異なります。
現在確認しているのは、ログイン時に公式PV検索が機能しないこと。ログイン時に歌詞の一部（ふりがな）から検索が機能していないこと。です。
それ以外にも見つかりそうな不具合ですが、バグの位置が同じ場所に固まってそうなので検証していません。よろしくお願いします。
歌詞の一部（ふりがな）検索では「ぱぷりかはながさいたら」で検証しました。

**Comment by garplab** [comment]
ありがとうございます！！対応しました
