### ISSUE TITLE
【要望】 一部の記号入力においてUSキーボード配列に対応して欲しい

### ISSUE THREAD

**Issue by rai-suta** [garplab/typingtube#62]
アンパサンド(&)の入力をUSキーボードにおける `Shift+7` で入力することができません。
一方、シングルクウォート(')についてはこれもUS配列とJIS配列で異なるキー配置となりますが、現状USキーボードからでも正常に入力を受け付けているようです。
設定項目にてキーボード種類を選択できるようにしていただけるとありがたいです。

**Comment by Toshi7878** [comment]
v12.5.6で修正しました
https://greasyfork.org/ja/scripts/400774-typing-tube-mod-official
