### ISSUE TITLE
「ん」の打鍵パターンの変化をhiraganaToRomaArray()の処理で対応する

### ISSUE THREAD

**Issue by Toshi7878** [garplab/typingtube#64]
hiraganaToRomaArray()のeach処理中に[n]→[nn]に置き換える処理を行えば
「ん」の打鍵パターンの変化を対応させたtyping_array&typing_array_roma配列を生成することができます。

現在の処理[next_char[0]=="ん"]の時にline_input_kana[0]の文字を見て変化させる処理だと、ローマ字表示モードでいきなり[n]が増えてしまう挙動になってしまい、総打鍵数表示も[nn]の数だけ少なくなってしまいます。

hiraganaToRomaArray()の処理を変更させるuser scriptを公開しました。
参考になれば幸いです
https://greasyfork.org/ja/scripts/403798-typing-tube-%E3%83%87%E3%83%90%E3%83%83%E3%82%B0-typing-array-typing-array-roma%E7%94%9F%E6%88%90%E6%99%82%E3%81%AB-%E3%82%93-%E3%81%AE%E6%89%93%E9%8D%B5%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3%E3%82%92%E5%A4%89%E6%9B%B4

**Comment by Toshi7878** [comment]
少しuser scriptを変更しました
半角文字全般でnnに変換されるのではなく、アルファベットのみnnに変換されるようにしました

**Comment by Toshi7878** [comment]
スクリプトを更新しました。[ゃ、ゅ、ょ]も含まれていたので、ひらがなの範囲指定を修正しました

**Comment by Toshi7878** [comment]
スクリプトを更新しました。入力できる文字の種類を増やしました
・句読点対応・全角記号対応(半角記号が対応している文字のみ)

**Comment by Toshi7878** [comment]
スクリプトを更新しました。

・「っ+小文字」の入力に対応。
・「いぇ」をile,ixeでも入力できるように修正
・キーボードで入力できる全ての全角記号に対応
・ゐ・ヰ・ゑ・ヱ対応

**Comment by garplab** [comment]
ありがとうございます。サーバ側の処理も変えないといけないから、まとまった時間があるときに対応します。

**Comment by Toshi7878** [comment]
スクリプトを更新しました。
「ん」の後続の文字が記号のときも[n]と[nn]のパターンで入力できるよう修正しました
