### ISSUE TITLE
【要望】タイピングデータのエスクポート&インポート

### ISSUE THREAD

**Issue by ryowta** [garplab/typingtube#73]
タイピングデータのCSVファイル等でのエスクポート&インポートを実装して欲しいですm(_ _)m

**Comment by garplab** [comment]
タイピングデータや歌詞が含まれるプレイ結果のダウンロード取得は権利使用料が高額になるため禁止です。
歌詞情報のコピーやツールを使ったり、プログラミングしての取得もしないようにしてください。

**Comment by ryowta** [comment]
了解しました。無知ですみません。
