### ISSUE TITLE
自分で作成したタイピングデータの複製

### ISSUE THREAD

**Issue by ryowta** [garplab/typingtube#74]
タイピングデータを他の同じ曲の違う動画でも利用したい

**Comment by ryowta** [comment]
他人が作成したデータのタイトルを変更して編集すると「タイトルを強制編集することはできません。コピー機能を利用して新たに作成してください」と表示されますが、コピー機能の使い方を教えて欲しいです。

**Comment by garplab** [comment]
編集画面の以下の箇所を探して動画IDを入力して実行してみてください
動画IDはプレイ画面URLの末尾の数字になります
<img width="725" alt="スクリーンショット 2020-06-13 19 27 55" src="https://user-images.githubusercontent.com/60339/84566433-0baba580-adac-11ea-8996-75af7f4d0a68.png">

**Comment by ryowta** [comment]
ありがとうございます。もう一つ質問なのですが、間違えて作ったデータの削除ってできますか？
