### ISSUE TITLE
【要望】練習モードの打/秒も正確に表示してほしい

### ISSUE THREAD

**Issue by Chronopolize** [garplab/typingtube#77]
現在練習モードの打/秒の計算は停止の時間はカウントされないので追いつかなくても必ずクリア速度以上の値を表示します。

**Comment by Toshi7878** [comment]
バージョン 18.6.8にて対応しました
サイト上に反映されるまでしばしお待ち下さい
https://greasyfork.org/ja/scripts/400774-typing-tube-mod-official
