### ISSUE TITLE
100%クリア時の打鍵数について

### ISSUE THREAD

**Issue by ghost** [garplab/typingtube#80]
100%クリア時，画像のように打数が合計打鍵数より多くなってしまうことがあります．

画像は https://typing-tube.net/movie/show/30806 プレイ時のものです．

![Screenshot-9](https://user-images.githubusercontent.com/61670437/85406154-57c0cc00-b59c-11ea-86e8-2055cfb8293d.jpg)

**Comment by Toshi7878** [comment]
曲の合計打鍵数はひらがなを最短で入力できるパターンから計算されていて
[ltuta],[silya],[chi]など打鍵パターンが多くなる入力をすると入力した合計打数が規定の打鍵数を超えてしまいますね

規定の打鍵数を超えた分、入力数を最適化する見方もできるので今のところは超えてしまうのは仕様にしています

**Comment by ghost** [comment]
なるほど，了解しました．
もし可能なら，最適化出来なかった分を別に表示するのも面白いかも…？
ただ実装が大変だとは思うので，これは後回しで大丈夫です．
