### ISSUE TITLE
【不具合】TypingResultのkey/secと初速抜きの値関係がおかしい

### ISSUE THREAD

**Issue by chan-nori** [garplab/typingtube#82]
お疲れ様です。

タイピング終了後に下にロールすると確認することができるTyping Result 内の値についてなのですが
表題の通り、key/secと初速抜きの値関係がおかしいように思われます。
初速抜きになるならkey/secの母数が減るわけなので必然的に値が大きくなるはずです。
おそらく表示している値が反転しているように思われます。

スクショを貼っておきますね！

![2e6d88fb8311eaab22ddb16dd66aaa5f](https://user-images.githubusercontent.com/38394567/86187427-bb3b9280-bb76-11ea-8812-e0f1aceef552.png)

以上。よろしくお願いいたします。

**Comment by Toshi7878** [comment]
ありがとうございます😊
v22.3.8にて修正されました
