### ISSUE TITLE
【不具合?】挑戦速度別にランキングを表示してほしいです｡

### ISSUE THREAD

**Issue by Ryo4499** [garplab/typingtube#90]
どの挑戦速度でやっても、同じランキングに登録されるため、自分の実力が分かりづらいです｡
また、注意事項に「スコア改竄等のチート行為、不正な登録、虚偽の申告など」とあったので、挑戦速度を遅くしてスコアを上げるのは十分改ざんだと思うのですが...
対応していただけるとうれしいです。よろしくお願いします。

**Comment by garplab** [comment]
#102

**Comment by garplab** [comment]
関連する課題があるためclose
