### ISSUE TITLE
【不具合】ユーザーページタイムラインの「リクエストをいいねしました」のURL

### ISSUE THREAD

**Issue by Toshi7878** [garplab/typingtube#91]
エディットページへのリンクが間違っています。

×　https://typing-tube.net/edit?videoid=???

○　https://typing-tube.net/movie/edit?videoid=???
![無題](https://user-images.githubusercontent.com/38578537/111627268-3abae000-8832-11eb-9e1b-224b5fc2333a.png)

**Comment by Toshi7878** [comment]
追記

URLの間違いが発生している場所はユーザーのプロフィール内にあるタイムラインのみみたいです。
![名称未設定](https://user-images.githubusercontent.com/38578537/113497507-e86f0400-953f-11eb-8717-0043f991b647.png)

**Comment by garplab** [comment]
修正しました
